// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/atex-concept/GlassTokens.tsx": () => import("../components/mockups/atex-concept/GlassTokens.tsx"),
  "./components/mockups/atex-concept/Landing.tsx": () => import("../components/mockups/atex-concept/Landing.tsx")
};
